.TH CONGRUITY "1" "March 2008" "congruity" "User Commands"
.SH NAME
congruity \- A simple GUI to program Logitech(R) Harmony(R) remotes
.SH SYNOPSIS
.B congruity
\fIFILE\fR
.SH DESCRIPTION
.B congruity
is intended to process files provided by the Logitech(R) Harmony(R)
configuration website, currently members.harmonyremote.com.
.PP
You should configure your web browser to execute
.B congruity
whenever a file of type EZHex, EZUp, or EZTut is downloaded.
.SH AUTHOR
Written by Stephen Warren.
.SH "REPORTING BUGS"
Report bugs to <concordance-devel@lists.sourceforge.net>.
.PP
.B congruity
utilitizes
.B libconcord.
Until
.B
congruity
grows its own sourceforge project, it piggy-backs off the
.B concordance/libconcord
mailing list.
.SH COPYRIGHT
Copyright \(co 2008 Stephen Warren.
.br
This is free software.  You may redistribute copies of it under the terms of
the GNU General Public License <http://www.gnu.org/licenses/gpl.html>.
There is NO WARRANTY, to the extent permitted by law.

